Add SPI acquisition for X-Heep
esl-epfl/biomedbench pull request #4
Opened 2024-09-25 15:05 UTC by FrancescoPoluzzi

- Added SPI acquisition in X-Heep
- updated README including X-Heep

2024-09-25 15:28 UTC, davideschiavone requested changes

2024-09-25 15:28 UTC, davideschiavone commented on Applications/Spi_Acquisition/README.md
> +This application reads a 768-Bytes buffer from a SPI ADC device. Macros are avaliable for debugging and profiling.
please write that one can optimize it (but do not do it) by using the DMA

2024-09-25 15:37 UTC, davideschiavone commented
LGTM, I let @DimitriosSamakovlis take care of extra revision and merge

2024-09-25 16:25 UTC, DimitriosSamakovlis commented
Overall looks good.

For consistency, please:
1. add the license + author/date structure at the top of your main.c (easy copy-paste from other files - put your name as main author)
2. move the Readme inside the x-Heep folder

Then you are all done!

2024-09-26 12:06 UTC, DimitriosSamakovlis approved these changes

2024-09-26 12:06 UTC, merged